[PR] Added Docker Example Usage / Support - Still needs support for multiple concurrent instances
aorumbayev/autogpt4all pull request #8
Opened 2023-06-07 06:17 UTC by zudsniper

# `[PR]` Merge docker examples by [`@juanfpo96`](https://github.com/juanfpo96)

This active fork by [`@juanfpo96`](https://github.com/juanfpo96) adds an example of how this application can be dockerized. 

---  

### Future Desires
I think this tool has lots of potential -- if it is done right. Here is whatever I think that means.  
- [ ] Add full `docker` support (include .env file vars for docker & docker related things, add CLI override flags for ease-of-use) 
- [ ] Add `docker-compose` support, enabling the building of custom images to be deployed -- with the local folder of a users project, for instance, as the last layer of the image.  
    > _I am no `docker` guru, so correct me if I say something stupid_   
  
- [ ] Add Multiple `Auto-GPT` Instance Support (parallel)
    - [ ] Implement a scheduling algorithm for mutually-exclusive resources to avoid deadlock/starvation 
    - [ ] Minimize mutually-exclusive resource use, make functionality as concurrent friendly as possible. 
    - [ ] Include `Event` emitters & listeners, as well as potentially a message queue system like rabbitmq. 
    - [ ] Essentially, just need a whole ass `AutoGPT-Instance-Manager` which is non-nominal work...  
- [ ] Web Management Panel 
    including an intricate panel system wherein the status of each `AGPT` instance can be monitored. Display health percentage of system. 

etc

<hr>

<b><a target="_blank" href="https://gh.zod.tf"><code>zod.tf</code></a></b> 

[![Discord](https://img.shields.io/discord/974855479975100487?label=tf2%20discord&color=9F2B68)](https://discord.gg/zodtf)  ![GitHub issue custom search](https://img.shields.io/github/issues-search?color=F8C8DC&label=issues&query=involves%3Azudsniper)  ![GitHub followers](https://img.shields.io/github/followers/zudsniper?style=social)  

> _fullstack development, server administration, web design, branding creation, musical composition & performance, video editing, and more probably_   

<a href="https://zod.tf/"><img src="https://i.imgur.com/oWKeLQq.gif" alt="zod.tf logo" width="120px" style="max-width: 100%;"></a>

2023-06-07 19:22 UTC, aorumbayev requested changes
Thanks for the submission @juanfpo96 , taking `Future Desires` aside please add additional details into PR description in regards to .devcontainer and how it can be initialized/configured from within IDEs like VScode or else. I will later update the readme based on your description + assuming we merge this. 

Please note both localai and gpt4all contain docker compose files already and are well optimized to be easily executed from docker. The reason for why i opted for building all sources manually is to avoid heuristics with allocated compute resources to docker vm and etc to run these models + the repo mainly served as an experimental playground to demonstrate how localai can integrate with gpt4all.

2023-06-07 19:22 UTC, aorumbayev commented on .env.template
> -OPENAI_API_BASE="http://localhost:8080"
please change this back to localhost OR introduce a new execution mode flag to the bash script so it replaces localhost with openapi if user selects docker during script execution

2023-06-08 18:38 UTC, juanfpo96 commented
Thank you, but I didn't ask to be merged as I'm in a WIP state with this. Once it is completed I will have a complete standalone version running in docker containers.

2023-06-08 18:52 UTC, zudsniper commented
> Thank you, but I didn't ask to be merged as I'm in a WIP state with this. Once it is completed I will have a complete standalone version running in docker containers.

my apologies @juanfpo96! I just saw your progress and created a PR.  

this is just a hardworking good programmer; he was gonna PR when he was ready, my bad.

2025-08-25 11:36 UTC, closed without merging